flags: {}

resolver: nightly-2016-04-16
compiler: ghcjs-0.2.0.820160416_ghc-7.10.3

compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.820160416_ghc-7.10.3:
         url: "https://tolysz.org/ghcjs/nightly-2016-04-16-820160416.tar.gz"

allow-newer: true

packages:
- location: '.'
- location:
    git: https://github.com/ryantrinkle/reflex.git
    commit: 3a7fb30dde160bc31c0bba4f42f7666ea6ca054a
  extra-dep: true
- location:
    git: https://github.com/tolysz/reflex-dom.git
    commit: 5318d581fe3ef7b2b0f70ac352d6c56700124b98
  extra-dep: true
- location:
     git: https://github.com/isomorphism/these.git
     commit: cf68c46bd049d23938f351da5618e9a09ef1102c

extra-deps:
  - ref-tf-0.4
  - these-0.6.1.0
  - ghcjs-dom-0.2.3.0
  - stateWriter-0.2.6
