flags: {}

resolver: lts-6.15
compiler: ghcjs-0.2.0.9006015_ghc-7.10.3

compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006015_ghc-7.10.3:
         url: "https://tolysz.org/ghcjs/lts-6.15-9006015.tar.gz"
         sha1: 4d513006622bf428a3c983ca927837e3d14ab687

allow-newer: true

packages:
- location: '.'
- location:
    git: https://github.com/ryantrinkle/reflex.git
    commit: f8338f6b68c9be4e8dcddbbab2098aeffa018535
  extra-dep: true

- location: 
    git: https://github.com/ryantrinkle/reflex-dom.git
    commit: e8b7d31fd2b6a8173e51096b7591ec346e33ad85
  extra-dep: true
- location:
     git: https://github.com/isomorphism/these.git
     commit: cf68c46bd049d23938f351da5618e9a09ef1102c
- location:
     git: https://github.com/reflex-frp/reflex-dom-contrib.git
     commit: d07180518168fb68a9ac2ec2df71f670e8d85e6b
  extra-dep: true

extra-deps:
- ref-tf-0.4.0.1
#- these-0.6.1.0
#- ghcjs-dom-0.2.4.0
#- ghcjs-dom-jsffi-0.3.1.0
# - ghcjs-dom-0.2.3.0
#- stateWriter-0.2.6
#- store-0.2.0.0
#- store-core-0.2.0.0
#- th-utilities-0.1.1.0
